version: "3.8"

services:

  configserver:
    image: 060896/bank_config_server:latest
    mem_limit: 700m
    ports:
      - "8030:8030"
    networks:
     - manh
      
  accounts:
    image: 060896/account_service:latest
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - manh
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8030/
  
  loans:
    image: 060896/loan_service:latest
    mem_limit: 700m
    ports:
      - "8010:8010"
    networks:
      - manh
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8030/
    
  cards:
    image: 060896/card_service:latest
    mem_limit: 700m
    ports:
      - "8020:8020"
    networks:
      - manh
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8030/
      
networks:
  manh: